export const CREATE_TODO = "CREATE_TODO";

export const LOAD_TODO_SUCCESS = "LOAD_TODO_SUCCESS";

export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";

export const DELETE_TODO = "DELETE_TODO";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";

export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";

export const UPDATE_TODO = "UPDATE_TODO";