/* eslint-disable */
export const FETHC_TODOS_REQUESTED = 'FETHC_TODOS_REQUESTED'
export const FETCH_TODOS_RECEIVED = 'FETCH_TODOS_RECEIVED'
export const FETCH_TODOS_ABORTED = 'FETCH_TODOS_ABORTED'
export const FETCH_TODOS_PENDING = 'FETCH_TODOS_PENDING'
export const FETCH_TODOS_FAILD = 'FETCH_TODOS_FAILD'

export const UPDATE_TODO = 'UPDATE_TODO'

export const ADD_TODO = 'ADD_TODO'
