const actionTypes = {
  'UPDATE_CURRENT_TAB': 'UPDATE_CURRENT_TAB',
  'APP_DATA': {
    'FETCH_APP_DATA_START': 'FETCH_APP_DATA_START',
    'FETCH_APP_DATA_SUCCESS': 'FETCH_APP_DATA_SUCCESS',
    'FETCH_APP_DATA_FAILED': 'FETCH_APP_DATA_FAILED',
    'FETCH_TAB_DATA_SUCCESS': 'FETCH_TAB_DATA_SUCCESS',
    'FETCH_TAB_DATA_FAILED': 'FETCH_TAB_DATA_FAILED'
  }
}

export default actionTypes;
