const actionTypes = {
  'UPDATE_CURRENT_TAB': 'UPDATE_CURRENT_TAB',
  'APP_DATA': {
    'FETCH_APP_DATA_START': 'FETCH_APP_DATA_START',
    'FETCH_APP_DATA_SUCCESS': 'FETCH_APP_DATA_SUCCESS',
    'FETCH_APP_DATA_FAILED': 'FETCH_APP_DATA_FAILED',
    'FETCH_TAB_DATA_SUCCESS': 'FETCH_TAB_DATA_SUCCESS',
    'FETCH_TAB_DATA_FAILED': 'FETCH_TAB_DATA_FAILED',
    'UPDATE_COUNT': 'UPDATE_COUNT',
    'UPDATE_BUCKETS': 'UPDATE_BUCKETS',
    'ADD_IN_BUCKETS': 'ADD_IN_BUCKETS'
  },
  'TASK': {
    'UPDATE_TASK': {
      'EDIT_THIS_TASK': 'EDIT_THIS_TASK',
      'CANCEL_EDIT': 'CANCEL_EDIT',
      'UPDATE_START': 'UPDATE_START',
      'UPDATE_SUCCESS': 'UPDATE_SUCCESS',
      'UPDATE_FAILED': 'UPDATE_FAILED'
    },
    'CREATE_TASK': {
      'CREATE_START': 'CREATE_START',
      'CREATE_SUCCESS': 'CREATE_SUCCESS',
      'CREATE_FAILED': 'CREATE_FAILED'
    }
  }
}

export default actionTypes;
