export const TASKS_FETCH_STARTED = 'TASK_FETCH_STARTED'
export const TASKS_FETCH_COMPLETED = 'TASKS_FETCH_COMPLETED'
export const TASKS_FETCH_FAILED = 'TASKS_FETCH_FAILED'

export const TASK_POST_STARTED = 'TASK_POST_STARTED'
export const TASK_POST_COMPLETED = 'TASK_POST_COMPLETED'
export const TASK_POST_FAILED = 'TASK_POST_FAILED'

export const SUB_TASK_POST_STARTED = 'SUB_TASK_POST_STARTED'
export const SUB_TASK_POST_COMPLETED = 'SUB_TASK_POST_COMPLETED'
export const SUB_TASK_POST_FAILED = 'SUB_TASK_POST_FAILED'

export const TASK_UPDATE_STARTED = 'TASK_UPDATE_STARTED'
export const TASK_UPDATE_COMPLETED = 'TASK_UPDATE_COMPLETED'
export const TASK_UPDATE_FAILED = 'TASK_UPDATE_FAILED'

export const SUB_TASK_UPDATE_STARTED = 'SUB_TASK_UPDATE_STARTED'
export const SUB_TASK_UPDATE_COMPLETED = 'SUB_TASK_UPDATE_COMPLETED'
export const SUB_TASK_UPDATE_FAILED = 'SUB_TASK_UPDATE_FAILED'

export const TASK_DELETE_STARTED = 'TASK_DELETE_STARTED'
export const TASK_DELETE_COMPLETED = 'TASK_DELETE_COMPLETED'
export const TASK_DELETE_FAILED = 'TASK_DELETE_FAILED'

export const SUB_TASK_DELETE_STARTED = 'SUB_TASK_DELETE_STARTED'
export const SUB_TASK_DELETE_COMPLETED = 'SUB_TASK_DELETE_COMPLETED'
export const SUB_TASK_DELETE_FAILED = 'SUB_TASK_DELETE_FAILED'
