export const REQUEST_TASKS_START = 'REQUEST_TASKS_START'
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS'
export const REQUEST_TASKS_FAILURE = 'REQUEST_TASKS_FAILURE'

export const ADD_NEW_TASK = 'ADD_NEW_TASK'
