export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const GET_TODOS = 'GET_TODOS';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODOS = 'UPDATE_TODOS';
export const UPDATE_SORT = 'UPDATE_SORT';
