module.exports = {
  GET_TASKS: 'GET_TASKS',
  ALL_TASKS: 'ALL_TASKS',
  ADD_TASK: 'ADD_TASK',
  TASK_ADDED: 'TASK_ADDED',
  DELETE_TASK: 'DELETE_TASK',
  TASK_DELETED: 'TASK_DELETED',
  UPDATE_TASK: 'UPDATE_TASK',
  TASK_UPDATED: 'TASK_UPDATED',
  ERROR: 'ERROR',
}
