const ADD_TASKS_FAILED = 'ADD_TASKS_FAILED';
const ADD_TASKS_SUCESSS = 'ADD_TASKS_SUCESSS';
const ADD_TASKS_REQUEST = 'ADD_TASKS_REQUEST';

export {
  ADD_TASKS_FAILED,
  ADD_TASKS_SUCESSS,
  ADD_TASKS_REQUEST,
};
