// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const MARK_TASK_COMPLETE = 'MARK_TASK_COMPLETE';
export const MARK_TASK_INCOMPLETE = 'MARK_TASK_INCOMPLETE';

export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const RECEIVE_TASK_SUCCESS = 'RECEIVE_TASK_SUCCESS';
export const RECEIVE_TASK_ERROR = 'RECEIVE_TASK_ERROR';

export const SELECT_TASK = 'SELECT_TASK';
export const UNSELECT_TASK = 'UNSELECT_TASK';

export const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST';
