// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const MARK_TASK_COMPLETE = 'MARK_TASK_COMPLETE';
export const MARK_TASK_INCOMPLETE = 'MARK_TASK_INCOMPLETE';

export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const RECEIVE_ALL_TASKS = 'RECEIVE_ALL_TASKS';

export const SELECT_TASK = 'SELECT_TASK';
export const UNSELECT_TASK = 'UNSELECT_TASK';
