export const actionTypes = {
  CHANGE: 'TODO_APP/TODO_FORM/CHANGE',
  SAVE: 'TODO_APP/TODO_FORM/SAVE',
  SAVE_SUCCESS: 'TODO_APP/TODO_FORM/SAVE_SUCCESS',
  SAVE_ERROR: 'TODO_APP/TODO_FORM/SAVE_ERROR'
};

export const key = 'TODO_FORM';
