export const REQUEST_TASKS_START = 'REQUEST_TASKS_START'
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS'
export const REQUEST_TASKS_FAILURE = 'REQUEST_TASKS_FAILURE'

export const ADD_TASK_START = 'ADD_TASK_START'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE'

export const UPDATE_TASK = 'UPDATE_TASK'

export const REMOVE_TASK_START = 'REMOVE_TASK_START'
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS'
export const REMOVE_TASK_FAILURE = 'REMOVE_TASK_FAILURE'
