export const actionTypes = {
  FETCH: 'TODO_APP/TODO_PAGE/FETCH',
  FETCH_SUCCESS: 'TODO_APP/TODO_PAGE/FETCH_SUCCESS',
  FETCH_ERROR: 'TODO_APP/TODO_PAGE/FETCH_ERROR',
  UPDATE: 'TODO_APP/TODO_PAGE/UPDATE',
  UPDATE_SUCCESS: 'TODO_APP/TODO_PAGE/UPDATE_SUCCESS',
  UPDATE_ERROR: 'TODO_APP/TODO_PAGE/UPDATE_ERROR',
  REMOVE: 'TODO_APP/TODO_PAGE/REMOVE',
  REMOVE_SUCCESS: 'TODO_APP/TODO_PAGE/REMOVE_SUCCESS',
  REMOVE_ERROR: 'TODO_APP/TODO_PAGE/REMOVE_ERROR'
};

export const key = 'TODO_PAGE';
