export const FETCH_TODO_LOADING = 'FETCH_TODO_LOADING';
export const FETCH_TODO_RECEIVED = 'FETCH_TODO_RECEIVED';
export const FETCH_TODO_ERROR = 'FETCH_TODO_ERROR';
export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
export const ADD_TODO_SAVED = 'ADD_TODO_SAVED';
export const REMOVE_TODO_LOADING = 'REMOVE_TODO_LOADING';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';
export const REMOVE_TODO_DELETED = 'REMOVE_TODO_DELETED';
export const SAVE_TODO_LOADING = 'SAVE_TODO_LOADING';
export const SAVE_TODO_ERROR = 'SAVE_TODO_ERROR';
export const SAVE_TODO_SAVED = 'SAVE_TODO_SAVED';
export const SET_FILTER = 'SET_FILTER';

export const EDIT_TODO = 'EDIT_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
