export const SAVEPENDING='SAVEPENDING';
export const SAVEFULFILLED='SAVEFULFILLED';
export const SAVEREJECTED='SAVEREJECTED';

export const GETPENDING='GETPENDING';
export const GETFULFILLED='GETFULFILLED';
export const GETREJECTED='GETREJECTED';

export const DELETEPENDING='DELETEPENDING';
export const DELETEFULFILLED='DELETEFULFILLED';
export const DELETEREJECTED='DELETEREJECTED';