const EDIT_TASKS_FAILED = 'EDIT_TASKS_FAILED';
const EDIT_TASKS_SUCESSS = 'EDIT_TASKS_SUCESSS';
const EDIT_TASKS_REQUEST = 'EDIT_TASKS_REQUEST';

// view selected item constants
const VIEW_TASKS_SUCESSS = 'VIEW_TASKS_SUCESSS';
const VIEW_TASKS_FAILED = 'VIEW_TASKS_FAILED';

export {
  EDIT_TASKS_FAILED,
  EDIT_TASKS_SUCESSS,
  EDIT_TASKS_REQUEST,
  VIEW_TASKS_SUCESSS,
  VIEW_TASKS_FAILED,
};
