export const SAVE_TASK_PENDING='SAVE_TASK_PENDING';
export const SAVE_TASK_FULFILLED='SAVE_TASK_FULFILLED';
export const SAVE_TASK_REJECTED='SAVE_TASK_REJECTED';

export const GET_TASK_PENDING='GET_TASK_PENDING';
export const GET_TASK_FULFILLED='GET_TASK_FULFILLED';
export const GET_TASK_REJECTED='GET_TASK_REJECTED';

export const DELETE_TASK_PENDING='DELETE_TASK_PENDING';
export const DELETE_TASK_FULFILLED='DELETE_TASK_FULFILLED';
export const DELETE_TASK_REJECTED='DELETE_TASK_REJECTED';