const LIST_TASKS_FAILED = 'LIST_TASKS_FAILED';
const LIST_TASKS_SUCESSS = 'LIST_TASKS_SUCESSS';
const LIST_TASKS_LOADING = 'LIST_TASKS_LOADING';
const LIST_TASKS_LOADED = 'LIST_TASKS_LOADED';

export {
  LIST_TASKS_FAILED,
  LIST_TASKS_SUCESSS,
  LIST_TASKS_LOADING,
  LIST_TASKS_LOADED,
};
