const LIST_TASKS_FAILED = 'LIST_TASKS_FAILED';
const LIST_TASKS_SUCESSS = 'LIST_TASKS_SUCESSS';
const LIST_TASKS_LOADING = 'LIST_TASKS_LOADING';
const LIST_TASKS_LOADED = 'LIST_TASKS_LOADED';
const SHOW_TASKS_SUCESSS = 'SHOW_TASKS_SUCESSS';

export {
  LIST_TASKS_FAILED,
  LIST_TASKS_SUCESSS,
  LIST_TASKS_LOADING,
  LIST_TASKS_LOADED,
  SHOW_TASKS_SUCESSS,
};
