const FETCH_TODOS = 'FETCH_TODOS';
// const REQUEST_TODOS = 'REQUEST_TODOS';
const LIST_TODOS = 'LIST_TODOS';

// const FETCH_TODO = 'FETCH_TODO';
// const REQUEST_TODO = 'REQUEST_TODO';
const LIST_TODO = 'LIST_TODO';

const CREATE_TODO = 'CREATE_TODO';
// const RECEIVE_CREATED_TODO = 'RECEIVE_CREATED_TODO';

const EDIT_TODO_TITLE = 'EDIT_TODO_TITLE';

const EDIT_TODO_DESCRIPTION = 'EDIT_TODO_DESCRIPTION';
const TOGGLE_TODO = 'TOGGLE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const APP_READY = 'APP_READY';
const APP_FETCHING = 'APP_FETCHING';

export default {
  FETCH_TODOS,
  LIST_TODOS,
  LIST_TODO,
  CREATE_TODO,
  EDIT_TODO_TITLE,
  EDIT_TODO_DESCRIPTION,
  TOGGLE_TODO,
  DELETE_TODO,
  APP_READY,
  APP_FETCHING,
};
