const LIST_TODOS = 'LIST_TODOS';
const LIST_TODO = 'LIST_TODO';
const CREATE_TODO = 'CREATE_TODO';
const EDIT_TODO_TITLE = 'EDIT_TODO_TITLE';
const EDIT_TODO_DESCRIPTION = 'EDIT_TODO_DESCRIPTION';
const TOGGLE_TODO = 'TOGGLE_TODO';
const DELETE_TODO = 'DELETE_TODO';

export default {
  LIST_TODOS,
  LIST_TODO,
  CREATE_TODO,
  EDIT_TODO_TITLE,
  EDIT_TODO_DESCRIPTION,
  TOGGLE_TODO,
  DELETE_TODO,
};
