const LIST_TODOS = 'LIST_TODOS';
const LIST_TODO = 'LIST_TODO';
const CREATE_TODO = 'CREATE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const DELETE_TODO = 'DELETE_TODO';

export default {
  LIST_TODOS,
  LIST_TODO,
  CREATE_TODO,
  EDIT_TODO,
  COMPLETE_TODO,
  DELETE_TODO,
};
