/* constants */
const GET_LANGUAGE = 'GET_LANGUAGE';
// modals
const TOGGLE_ABOUT_MODAL = 'TOGGLE_ABOUT_MODAL';
// current task
const CURRENT_TASK_DELETE = 'CURRENT_TASK_DELETE';
// task post
const TASK_POST_REQUESTED = 'TASK_POST_REQUESTED';
const TASK_POST_SUCCEEDED = 'TASK_POST_SUCCEEDED';
const TASK_POST_FAILED = 'TASK_POST_FAILED';
// task delete
const TASK_DELETE_REQUESTED = 'TASK_DELETE_REQUESTED';
const TASK_DELETE_SUCCEEDED = 'TASK_DELETE_SUCCEEDED';
const TASK_DELETE_FAILED = 'TASK_DELETE_FAILED';
// task update
const TASK_UPDATE_REQUESTED = 'TASK_UPDATE_REQUESTED';
const TASK_UPDATE_SUCCEEDED = 'TASK_UPDATE_SUCCEEDED';
const TASK_UPDATE_FAILED = 'TASK_UPDATE_FAILED';
// task get
const TASK_GET_REQUESTED = 'TASK_GET_REQUESTED';
const TASK_GET_SUCCEEDED = 'TASK_GET_SUCCEEDED';
const TASK_GET_FAILED = 'TASK_GET_FAILED';
// tasks get
const TASKS_GET_REQUESTED = 'TASKS_GET_REQUESTED';
const TASKS_GET_SUCCEEDED = 'TASKS_GET_SUCCEEDED';
const TASKS_GET_FAILED = 'TASKS_GET_FAILED';
// task status
const TASK_NEW_STATUS = 'TASK_NEW_STATUS';
export {
	GET_LANGUAGE,

	TOGGLE_ABOUT_MODAL,

	CURRENT_TASK_DELETE,

	TASK_POST_REQUESTED,
	TASK_POST_SUCCEEDED,
	TASK_POST_FAILED,

	TASK_DELETE_REQUESTED,
	TASK_DELETE_SUCCEEDED,
	TASK_DELETE_FAILED,

	TASK_UPDATE_REQUESTED,
	TASK_UPDATE_SUCCEEDED,
	TASK_UPDATE_FAILED,

	TASK_GET_REQUESTED,
	TASK_GET_SUCCEEDED,
	TASK_GET_FAILED,

	TASKS_GET_REQUESTED,
	TASKS_GET_SUCCEEDED,
	TASKS_GET_FAILED,

	TASK_NEW_STATUS
};
