/* constants */
const GET_LANGUAGE = 'GET_LANGUAGE';
const TOGGLE_ABOUT_MODAL = 'TOGGLE_ABOUT_MODAL';
const TOGGLE_TASK_MODAL = 'TOGGLE_TASK_MODAL';
export {
	GET_LANGUAGE,
	TOGGLE_ABOUT_MODAL,
	TOGGLE_TASK_MODAL
};
