export const TASKS_FETCH_START = 'TASKS_FETCH_START'
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS'
export const TASKS_FETCH_FAIL = 'TASKS_FETCH_FAIL'

export const TASK_ADD_START = 'TASK_ADD_START'
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS'
export const TASK_ADD_FAIL = 'TASK_ADD_FAIL'

export const TASK_SELECTED = 'TASK_SELECTED'
export const TASK_EDIT = 'TASK_EDIT'

export const TASK_DELETE_START = 'TASK_DELETE_START'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'
