export const REQUEST_TODOS = 'REQUEST_TODOS';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const CANCEL_REQUEST_TODOS = 'CANCEL_REQUEST_TODOS';

export const REQUEST_TODO = 'REQUEST_TODO';
export const RECEIVE_TODO = 'RECEIVE_TODO';
export const CANCEL_REQUEST_TODO = 'CANCEL_REQUEST_TODO';

export const REQUEST_TODO_ADD = 'REQUEST_TODO_ADD';
export const RECEIVE_TODO_ADD = 'RECEIVE_TODO_ADD';
export const CANCEL_REQUEST_TODO_ADD = 'CANCEL_REQUEST_TODO_ADD';

export const REQUEST_TODO_DELETE = 'REQUEST_TODO_DELETE';
export const RECEIVE_TODO_DELETE = 'RECEIVE_TODO_DELETE';
export const CANCEL_REQUEST_TODO_DELETE = 'CANCEL_REQUEST_TODO_DELETE';

export const REQUEST_TODO_UPDATE = 'REQUEST_TODO_UPDATE';
export const RECEIVE_TODO_UPDATE = 'RECEIVE_TODO_UPDATE';
export const CANCEL_REQUEST_TODO_UPDATE = 'CANCEL_REQUEST_TODO_UPDATE';
